### ISSUE TITLE
Duplicate Protobuf Message Name Error in Jest Tests

### ISSUE THREAD

**Issue by ThomasMeetKai** [KurtzL/nestjs-temporal#41]
Hello,

I'm currently facing an issue while trying to run unit tests with Jest for Temporal activities in a NestJS application using the `nestjs-temporal` module. When running my tests, I get the following error:

```
 FAIL  src/temporal/activities/blackjack.activity.spec.ts
  ● Test suite failed to run
                                                                                                                                              
    duplicate name 'ActivityHeartbeat' in Namespace coresdk

      3 | import { Injector } from '@nestjs/core/injector/injector';
      4 | import { InstanceWrapper } from '@nestjs/core/injector/instance-wrapper';
    > 5 | import { NativeConnection, NativeConnectionOptions, Runtime, RuntimeOptions, Worker, WorkerOptions } from '@temporalio/worker';     
        | ^
      6 |
      7 | import { TEMPORAL_CONNECTION_CONFIG, TEMPORAL_CORE_CONFIG, TEMPORAL_WORKER_CONFIG } from './temporal.constants';
      8 | import { TemporalMetadataAccessor } from './temporal-metadata.accessors';

      at Namespace.add (node_modules/protobufjs/src/namespace.js:239:23)
      at Root.add (node_modules/protobufjs/src/namespace.js:232:28)
      at Root.addJSON (node_modules/protobufjs/src/namespace.js:172:16)
      at Object.<anonymous> (node_modules/@temporalio/common/node_modules/@temporalio/proto/protos/json-module.js:7:2)
      at Object.<anonymous> (node_modules/@temporalio/common/node_modules/@temporalio/proto/protos/root.js:8:23)
      at Object.<anonymous> (node_modules/@temporalio/common/node_modules/@temporalio/proto/protos/index.js:1:100)
      at Object.<anonymous> (node_modules/@temporalio/common/src/proto-utils.ts:2:1)
      at Object.<anonymous> (node_modules/@temporalio/worker/src/worker.ts:52:1)
      at Object.<anonymous> (node_modules/@temporalio/worker/src/debug-replayer/index.ts:4:1)
      at Object.<anonymous> (node_modules/@temporalio/worker/src/index.ts:25:1)
      at Object.<anonymous> (src/libs/nestjs-temporal/temporal.explorer.ts:5:1)
      at Object.<anonymous> (src/libs/nestjs-temporal/temporal.module.ts:6:1)
      at Object.<anonymous> (src/libs/nestjs-temporal/index.ts:1:1)
      at Object.<anonymous> (src/temporal/activities/blackjack.activity.ts:12:1)
      at Object.<anonymous> (src/temporal/activities/blackjack.activity.spec.ts:5:1)
   ```

This seems to suggest that the `ActivityHeartbeat` message is being defined more than once in the same namespace. Is the NestJS Temporal module causing this conflict?

Here's the context for when the issue arises:

I have an activity in my application:

```
@Activity()
  async verifyLimit(bet: BlackjackBetSlip): Promise<boolean> {
    ...
  }
```

And I'm trying to write a Jest test for it, like so:
```
import { MockActivityEnvironment } from '@temporalio/testing';
import { BlackjackBetSlip } from '../types/blackjack';
import { Currency } from '../types/roulette';
import { Decimal } from '@prisma/client/runtime';
import assert from 'assert';
import { BlackjackActivity } from './blackjack.activity';
const { verifyLimit } = BlackjackActivity;

const env = new MockActivityEnvironment();
describe('verifyLimit activity', () => {
  it('should return true for valid bet', async () => {
    const bet: BlackjackBetSlip = {
      amount: new Decimal(1000),
      currency: Currency.NILET,
      gameLogId: 'test',
      idempotencyKey: 'test',
      userId: 'test',
    };

    const result = await env.run(verifyLimit, bet);
    assert.equal(result, true);
  });
});
```
Is there a known workaround, or could this be a bug or incompatibility in the 'nestjs-temporal' module itself?

**Comment by ThomasMeetKai** [comment]
Figured it out, nestjs-temporal was built with temporal version 1.4.0, so I had to downgrade my versions as well.
