### ISSUE TITLE
TemporalModule.registerClientAsync ignores providers passed to the dynamic module

### ISSUE THREAD

**Issue by koppa96** [KurtzL/nestjs-temporal#53]
I have the following code, which is quite similar to the example code provided for manually creating a connection.

```ts
TemporalModule.registerClientAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: async (config: ConfigService) => {
    const temporalHost = config.get('TEMPORAL_URL', 'localhost:7233')
    const connection = await Connection.connect({
      address: temporalHost
    })

    return {
      connection
    }
  }
})
```

However I can't seem to make it work, because I get the following error:

```txt
Error: Nest can't resolve dependencies of the TemporalAsyncQueue_default (?). Please make sure that the argument ConfigService at index [0] is available in the TemporalModule context.

Potential solutions:
- If ConfigService is a provider, is it part of the current TemporalModule?
- If ConfigService is exported from a separate @Module, is that module imported within TemporalModule?
  @Module({
    imports: [ /* the Module containing ConfigService */ ]
  })

    at Injector.lookupComponentInParentModules (C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\injector.js:241:19)
    at Injector.resolveComponentInstance (C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\injector.js:194:33)
    at resolveParam (C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\injector.js:116:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\injector.js:131:27)
    at Injector.loadInstance (C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\injector.js:57:13)
    at Injector.loadProvider (C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\injector.js:84:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\instance-loader.js:44:9)
    at C:\Users\koppa.peter\Desktop\mti-hirugynokseg\src\sites\node_modules\.pnpm\@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0\node_modules\@nestjs\core\injector\instance-loader.js:29:13
```

I tried to look into the source code and `TemporalModule.registerClientAsync` and the functions that invokes doesn't seem to do anything with the imports of the provided object.

**Comment by mawaldne** [comment]
Also having this issue.

**Comment by MrCasimiro** [comment]
Just as a note, this can be easily fixed, just need to update the `registerClientAsync` method and add to the return clause `imports: asyncSharedWorkflowClientOptions.imports`
