### ISSUE TITLE
Cannot read properties of undefined (reading 'install')

### ISSUE THREAD

**Issue by fjur** [KurtzL/nestjs-temporal#7]
Running into the following error when trying to run your project, installed via npm version 0.0.5 https://www.npmjs.com/package/nestjs-temporal

It seems that it thinks the core package from @temporal/worker is undefined

```
/node_modules/nestjs-temporal/dist/temporal.explorer.js:55
                yield worker_1.Core.install(coreConfig);
                                    ^
TypeError: Cannot read properties of undefined (reading 'install')
    at TemporalExplorer.<anonymous> (/node_modules/nestjs-temporal/dist/temporal.explorer.js:55:37)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/nestjs-temporal/dist/temporal.explorer.js:14:58)
```

Also, how does this package work, does it boot up a worker service that listens on the same process as the controllers? Trying to implement this in a monolith where there are two separate apps, one that deals with API endpoints (controller), and the worker that solely runs workflows and activities

**Comment by yuvall-cyera** [comment]
I have the same problem

**Comment by yuvall-cyera** [comment]
The problem was that this repository relied on @temporalio/worker version 0.18.0, while I installed the latest one...
